### ISSUE TITLE
CLI - Issues upgrading ova to current sift through proxy

### ISSUE THREAD

**Issue by johnmccash** [teamdfir/sift#324]
After installing the current ova download in vmware, and running apt-get upgrade, I attempted to upgrade it to the current sift version (through our internet proxy) using the CLI. This fails with the following error:

$ sift upgrade
> sift-cli@1.7.1-master.f1177e4
> sift-version: v2018.16.0

write EPROTO 140672849012544:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:

Error: write EPROTO 140672849012544:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:

    at module.exports.__dirname.sendError (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/github/lib/index.js:854:19)
    at /snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/github/lib/index.js:865:29
    at callCallback (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/github/lib/index.js:728:17)
    at ClientRequest.<anonymous> (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/github/lib/index.js:807:17)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at emitErr (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/agent-base/agent.js:88:11)
    at /snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/agent-base/agent.js:99:9
    at TLSSocket.onerror (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/https-proxy-agent/https-proxy-agent.js:104:5)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at onwriteError (_stream_writable.js:341:10)
    at onwrite (_stream_writable.js:359:5)
    at fireErrorCallbacks (net.js:481:13)
    at TLSSocket.Socket._destroy (net.js:522:3)
    at WriteWrap.afterWrite [as oncomplete] (net.js:816:10)

**Comment by ekristen** [comment]
Generally that's the sort of error you get when it's attempting to either talk SSL to something that can't talk SSL or it truly has a version of SSL that's unknown and unsupported.

**Comment by johnmccash** [comment]
Still an issue for me... Anyone know of a way to get this to work through a proxy? I was able to get it to work in one previous version, and posted the specific steps required in Issue #236, but they no longer work...
