### ISSUE TITLE
Installation breaks and cannot be completed or fixed (physical machine)

### ISSUE THREAD

**Issue by socialcred** [teamdfir/sift#355]
Last week I successfully built a V3 VM, but now am having a new issue when building a physical V3 machine.  The initial installation had one error that seemed to be a broken ophcrack package.  I figured I could remedy the situation by simply performing another "sudo sift install" to fix things.  Instead I get the following error message:

> sift-cli@1.7.1-master.f1177e4
> sift-version: notinstalled

> downloading v2019.06.0
>> downloading sift-saltstack-v2019.06.0.tar.gz.asc
>> downloading sift-saltstack-v2019.06.0.tar.gz.sha256
>> downloading sift-saltstack-v2019.06.0.tar.gz.sha256.asc
>> downloading sift-saltstack-v2019.06.0.tar.gz
> validating file sift-saltstack-v2019.06.0.tar.gz
> validating signature for sift-saltstack-v2019.06.0.tar.gz.sha256
> extracting update sift-saltstack-v2019.06.0.tar.gz
> performing update v2019.06.0
>> Log file: /var/cache/sift/cli/v2019.06.0/saltstack.log

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.update.on (/snapshot/Users/ekristen/Development/sift/sift-cli/sift-cli.js:520:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

Any ideas as to why this error is occuring or a better way to fix the installation.  Most tools, posters, desktop appear to be proper for the SIFT V3, but any attempt to update or install causes errors.

I used a fully updated 16.04 base system to build the machine before using the sift cli.

**Comment by ekristen** [comment]
Pleas attach the log file

**Comment by socialcred** [comment]
The log content is as follows:

Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 386, in salt_call
    import salt.cli.call
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 9, in <module>
    import salt.cli.caller
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 19, in <module>
    import salt.minion
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 90, in <module>
    import salt.pillar
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 18, in <module>
    import salt.fileclient
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 29, in <module>
    import salt.utils.templates
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 31, in <module>
    import salt.utils.http
  File "/usr/lib/python2.7/dist-packages/salt/utils/http.py", line 71, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

**Comment by ekristen** [comment]
Reinstall pyopenssl. It’s not clear why this happens

**Comment by socialcred** [comment]
I get the following result when trying to re-install:
pip install pyopenssl
Requirement already satisfied: pyopenssl in /usr/lib/python2.7/dist-packages

Should I remove it first and then reinstall?

**Comment by ekristen** [comment]
Or force reinstall option

**Comment by socialcred** [comment]
Dear Erik,

Forcing the reinstallation of pyopenssl followed by a sudo sift install fixed the problem.  Thanks for the tip!
