### ISSUE TITLE
[CLI] Problem with Windows 10 Ubuntu CLI Install

### ISSUE THREAD

**Issue by guardian703** [teamdfir/sift#366]
getting the following errors after following the instructions:

$ sudo sift install
> sift-cli@1.7.1-master.f1177e4
> sift-version: notinstalled

> downloading v2019.06.0
>> downloading sift-saltstack-v2019.06.0.tar.gz.asc
>> downloading sift-saltstack-v2019.06.0.tar.gz.sha256
>> downloading sift-saltstack-v2019.06.0.tar.gz.sha256.asc
>> downloading sift-saltstack-v2019.06.0.tar.gz
> validating file sift-saltstack-v2019.06.0.tar.gz
> validating signature for sift-saltstack-v2019.06.0.tar.gz.sha256
> extracting update sift-saltstack-v2019.06.0.tar.gz
> performing update v2019.06.0
>> Log file: /var/cache/sift/cli/v2019.06.0/saltstack.log

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.update.on (/snapshot/Users/ekristen/Development/sift/sift-cli/sift-cli.js:520:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by dspransy** [comment]
Had the same issue today installing SIFT on a brand new Ubuntu 16.04.6 (AWS provided AMI) system. 

Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 386, in salt_call
    import salt.cli.call
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 9, in <module>
    import salt.cli.caller
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 19, in <module>
    import salt.minion
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 90, in <module>
    import salt.pillar
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 18, in <module>
    import salt.fileclient
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 29, in <module>
    import salt.utils.templates
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 31, in <module>
    import salt.utils.http
  File "/usr/lib/python2.7/dist-packages/salt/utils/http.py", line 71, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

Linux siftworkstation 4.4.0-1075-aws #85-Ubuntu SMP Thu Jan 17 17:15:12 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ekristen** [comment]
Re install pyopenssl

**Comment by guardian703** [comment]
That worked, but just decided to switch over completely to a new Ubuntu install to separate disk.
