### ISSUE TITLE
Error installing latest version

### ISSUE THREAD

**Issue by gedeon8084** [teamdfir/sift#376]
Hi! I am getting an error installing the latest version on ubuntu 16.04.
`$ sudo sift install --no-cache
[sudo] password for pagz: 
> sift-cli@1.7.1-master.f1177e4
> sift-version: notinstalled

> downloading v2019.06.0
>> downloading sift-saltstack-v2019.06.0.tar.gz.asc
>> downloading sift-saltstack-v2019.06.0.tar.gz.sha256
>> downloading sift-saltstack-v2019.06.0.tar.gz.sha256.asc
>> downloading sift-saltstack-v2019.06.0.tar.gz
> validating file sift-saltstack-v2019.06.0.tar.gz
> validating signature for sift-saltstack-v2019.06.0.tar.gz.sha256
> extracting update sift-saltstack-v2019.06.0.tar.gz
> performing update v2019.06.0
>> Log file: /var/cache/sift/cli/v2019.06.0/saltstack.log

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.update.on (/snapshot/Users/ekristen/Development/sift/sift-cli/sift-cli.js:520:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12)`

And here is the saltstack log
`Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 386, in salt_call
    import salt.cli.call
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 9, in <module>
    import salt.cli.caller
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 19, in <module>
    import salt.minion
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 90, in <module>
    import salt.pillar
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 18, in <module>
    import salt.fileclient
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 29, in <module>
    import salt.utils.templates
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 31, in <module>
    import salt.utils.http
  File "/usr/lib/python2.7/dist-packages/salt/utils/http.py", line 71, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'`

Hope it helps,

Best Regards,

pablo

**Comment by ekristen** [comment]
Re install pyopenssl

**Comment by gedeon8084** [comment]
Thank you! It is installing normally now!

**Comment by gedeon8084** [comment]
Ok. After reinstalling the whole system again, several times. It keeps breaking up at the same spot.
And I am back were we started.
If I try to install pyopenssl, this is what I get
> sudo pip install pyopenssl
Requirement already satisfied: pyopenssl in /usr/lib/python2.7/dist-packages
You are using pip version 9.0.1, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

The error once again is 
`pagz@workstation:~$ sudo sift install --no-cache
> sift-cli@1.7.1-master.f1177e4
> sift-version: notinstalled

> downloading v2019.06.0
>> downloading sift-saltstack-v2019.06.0.tar.gz.asc
>> downloading sift-saltstack-v2019.06.0.tar.gz.sha256
>> downloading sift-saltstack-v2019.06.0.tar.gz.sha256.asc
>> downloading sift-saltstack-v2019.06.0.tar.gz
> validating file sift-saltstack-v2019.06.0.tar.gz
> validating signature for sift-saltstack-v2019.06.0.tar.gz.sha256
> extracting update sift-saltstack-v2019.06.0.tar.gz
> performing update v2019.06.0
>> Log file: /var/cache/sift/cli/v2019.06.0/saltstack.log

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.update.on (/snapshot/Users/ekristen/Development/sift/sift-cli/sift-cli.js:520:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12)
`

And the saltstack is

> Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 386, in salt_call
    import salt.cli.call
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 9, in <module>
    import salt.cli.caller
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 19, in <module>
    import salt.minion
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 90, in <module>
    import salt.pillar
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 18, in <module>
    import salt.fileclient
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 29, in <module>
    import salt.utils.templates
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 31, in <module>
    import salt.utils.http
  File "/usr/lib/python2.7/dist-packages/salt/utils/http.py", line 71, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

What I am missing?

**Comment by gedeon8084** [comment]
If I run 

> pip install --force-reinstall pyopenssl

> 
It will install the latest version, Is this what you want me to do?

Best Regards,

pablo

**Comment by ekristen** [comment]
Yes.

**Comment by gedeon8084** [comment]
This is the result

> sudo pip install --force-reinstall pyopenssl
Requirement already satisfied: pyopenssl in /usr/lib/python2.7/dist-packages
You are using pip version 9.0.1, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

> 
It appears that for some reason it is not reinstalling. I am doing it right?

**Comment by ekristen** [comment]
try 

```
pip install --upgrade --force-reinstall pyopenssl
```

**Comment by gedeon8084** [comment]
Resintalling pyopenssl worked!
 this is the result
`sudo pip install --upgrade --force-reinstall pyopensslCollecting pyopenssl
  Downloading https://files.pythonhosted.org/packages/01/c8/ceb170d81bd3941cbeb9940fc6cc2ef2ca4288d0ca8929ea4db5905d904d/pyOpenSSL-19.0.0-py2.py3-none-any.whl (53kB)
    100% |████████████████████████████████| 61kB 1.2MB/s 
Collecting six>=1.5.2 (from pyopenssl)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting cryptography>=2.3 (from pyopenssl)
  Downloading https://files.pythonhosted.org/packages/e6/68/50698ce24c61db7d44d93a5043c621a0ca7839d4ef9dff913e6ab465fc92/cryptography-2.7-cp27-cp27mu-manylinux1_x86_64.whl (2.3MB)
    100% |████████████████████████████████| 2.3MB 225kB/s 
Collecting enum34; python_version < "3" (from cryptography>=2.3->pyopenssl)
  Downloading https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting cffi!=1.11.3,>=1.8 (from cryptography>=2.3->pyopenssl)
  Downloading https://files.pythonhosted.org/packages/8d/e9/0c8afd1579e5cf7bc0f06fbcd7cdb954cbc0baadd505973949a99337da1c/cffi-1.12.3-cp27-cp27mu-manylinux1_x86_64.whl (415kB)
    100% |████████████████████████████████| 419kB 1.1MB/s 
Collecting asn1crypto>=0.21.0 (from cryptography>=2.3->pyopenssl)
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting ipaddress; python_version < "3" (from cryptography>=2.3->pyopenssl)
  Using cached https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography>=2.3->pyopenssl)
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
    100% |████████████████████████████████| 163kB 1.4MB/s 
Building wheels for collected packages: pycparser
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /home/pagz/.cache/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511
Successfully built pycparser
Installing collected packages: six, enum34, pycparser, cffi, asn1crypto, ipaddress, cryptography, pyopenssl
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Found existing installation: enum34 1.1.6
    Uninstalling enum34-1.1.6:
      Successfully uninstalled enum34-1.1.6
  Found existing installation: pycparser 2.18
    Uninstalling pycparser-2.18:
      Successfully uninstalled pycparser-2.18
  Found existing installation: cffi 1.10.0
    Uninstalling cffi-1.10.0:
      Successfully uninstalled cffi-1.10.0
  Found existing installation: asn1crypto 0.24.0
    Uninstalling asn1crypto-0.24.0:
      Successfully uninstalled asn1crypto-0.24.0
  Found existing installation: ipaddress 1.0.22
    Uninstalling ipaddress-1.0.22:
      Successfully uninstalled ipaddress-1.0.22
  Found existing installation: cryptography 2.4.1
    Uninstalling cryptography-2.4.1:
      Successfully uninstalled cryptography-2.4.1
  Found existing installation: pyOpenSSL 0.15.1
    Uninstalling pyOpenSSL-0.15.1:
      Successfully uninstalled pyOpenSSL-0.15.1
Successfully installed asn1crypto-0.24.0 cffi-1.12.3 cryptography-2.7 enum34-1.1.6 ipaddress-1.0.22 pycparser-2.19 pyopenssl-19.0.0 six-1.12.0
You are using pip version 9.0.1, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

> 
The installation it is on its way again. I will let you know how it goes so we can close this.
Thank you!
