### ISSUE TITLE
Unable to install SIFT - Ubuntu 14.04.6 LTS

### ISSUE THREAD

**Issue by bmi000** [teamdfir/sift#383]
Hi:
im getting below error when i try to install sift:

remnux@remnux:~$ sudo sift install
> sift-cli@1.7.1-master.f1177e4
> sift-version: notinstalled

Installing and configuring SaltStack properly ...

Command failed: apt-get install -y --allow-change-held-packages salt-minion
E: Command line option --allow-change-held-packages is not understood

Error: Command failed: apt-get install -y --allow-change-held-packages salt-minion
E: Command line option --allow-change-held-packages is not understood

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12)
remnux@remnux:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.6 LTS
Release:	14.04
Codename:	trusty

**Comment by ekristen** [comment]
14.04 is not supported

**Comment by bmi000** [comment]
Thanks
So we can't anymore install SIFT on remnux?
