### ISSUE TITLE
Volatility Yarascan is throwing an error

### ISSUE THREAD

**Issue by r4f1** [teamdfir/sift#389]
When using yarascan plugin in volatility I get the error shown below. Can you advise how to resolve this please?

```
vol.py -f ~/Desktop/CTF/OtterCTF/what_the_password_COMPLETED/OtterCTF.vmem --profile=Win7SP1x64 yarascan -Y "Th3"

Volatility Foundation Volatility Framework 2.6
Traceback (most recent call last):
  File "/usr/bin/vol.py", line 192, in <module>
    main()
  File "/usr/bin/vol.py", line 174, in main
    command = cmds[module](config)
  File "/usr/lib/python2.7/dist-packages/volatility/plugins/malware/malfind.py", line 190, in __init__
    help = 'Make the search case insensitive')        
  File "/usr/lib/python2.7/dist-packages/volatility/conf.py", line 363, in add_option
    self.optparser.add_option("-{0}".format(short_option), "--{0}".format(option), **args)
  File "/usr/lib/python2.7/optparse.py", line 1021, in add_option
    self._check_conflict(option)
  File "/usr/lib/python2.7/optparse.py", line 996, in _check_conflict
    option)
optparse.OptionConflictError: option -C/--case: conflicting option string(s): -C
`
```

**Comment by ulisesrc** [comment]
Edit this:
I found a workaround:
Edit the malfind.py file at /usr/lib/python2.7/dist-packages/volatility/plugins/malware/malfind.py

change the short option at Line 189, Original is Capital C letter. In my case I change it to small c letter
config.add_option("CASE", short_option = 'c', default = False, action = 'store_true',

change the short option at Line 195. Original is Capital Y Letter. In my case I change it to capital U letter
config.add_option('YARA-RULES', short_option = 'U', default = None,

Make sure to backup the original file.

Original: https://github.com/teamdfir/sift/issues/218

**Comment by dewiestr** [comment]
This issue is still in the latest SIFT FYI ...

**Comment by ekristen** [comment]
Looks like this is the case of conflicting plugins unfortunately. You can try disabling the malware one for now. We try to be very selective in which plugins are added and sometimes conflicts arise because authors use the same CLI options.
