### ISSUE TITLE
when installing sift on ubuntu 16.04 in AWS S3, it's giving this below error: please urgent solution needed

### ISSUE THREAD

**Issue by rushabhladhani** [teamdfir/sift#393]
sift install
> sift-cli@1.7.1-master.f1177e4
> sift-version: notinstalled

> downloading v2019.06.0
>> downloading sift-saltstack-v2019.06.0.tar.gz.asc
>> downloading sift-saltstack-v2019.06.0.tar.gz.sha256
>> downloading sift-saltstack-v2019.06.0.tar.gz.sha256.asc
>> downloading sift-saltstack-v2019.06.0.tar.gz
> validating file sift-saltstack-v2019.06.0.tar.gz
> validating signature for sift-saltstack-v2019.06.0.tar.gz.sha256
> extracting update sift-saltstack-v2019.06.0.tar.gz
> performing update v2019.06.0
>> Log file: /var/cache/sift/cli/v2019.06.0/saltstack.log

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.update.on (/snapshot/Users/ekristen/Development/sift/sift-cli/sift-cli.js:520:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by ekristen** [comment]
What does this file say? /var/cache/sift/cli/v2019.06.0/saltstack.log

**Comment by rushabhladhani** [comment]
this file giving below:
root@ip-172-31-91-212:/var/cache/sift/cli/v2019.06.0# cat saltstack.log
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 391, in salt_call
    import salt.cli.call
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 9, in <module>
    import salt.cli.caller
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 19, in <module>
    import salt.minion
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 78, in <module>
    import salt.pillar
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 18, in <module>
    import salt.fileclient
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 29, in <module>
    import salt.utils.templates
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 31, in <module>
    import salt.utils.http
  File "/usr/lib/python2.7/dist-packages/salt/utils/http.py", line 71, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
root@ip-172-31-91-212:/var/cache/sift/cli/v2019.06.0#

**Comment by ekristen** [comment]
Reinstall pyopenssl

**Comment by rushabhladhani** [comment]
root@ip-:/var/cache/sift/cli/v2019.06.0# sudo apt --purge remove pyopenssl
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package pyopenssl


i have read your previous solutions but i couldnt purge or remove this pyopenssl

**Comment by rushabhladhani** [comment]
root@ip-:/var/cache/sift/cli/v2019.06.0# pip install pyopenssl
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/main.py", line 45, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/commands/install.py", line 23, in <module>
    from pip._internal.cli.req_command import RequirementCommand
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/req_command.py", line 20, in <module>
    from pip._internal.network.session import PipSession
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/network/session.py", line 17, in <module>
    from pip._vendor import requests, six, urllib3
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py", line 97, in <module>
    from pip._vendor.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

**Comment by ekristen** [comment]
apt install pyopenssl

**Comment by rushabhladhani** [comment]
root@ip-:/usr/local/bin# apt install pyopenssl
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package pyopenssl
root@ip-2:/usr/local/bin#

**Comment by starskizzle** [comment]
Same issue, Fresh ubuntu 16.04 install. followed SIFT install instructions via https://github.com/teamdfir/sift-cli#installation

**Comment by ekristen** [comment]
reinstall https://www.pyopenssl.org/en/stable/install.html
