### ISSUE TITLE
[saltstack] python module install issues 16.04 - defang, machinae

### ISSUE THREAD

**Issue by Sandriekus** [teamdfir/sift#401]
Hi,

I'm trying to install sift on Ubuntu 16.04.06 - desktop (VMware virtual machine).

My installation:
```
sudo sift version
> sift-cli@1.7.1-master.f1177e4
> sift-version: notinstalled
```

Command: sudo sift install --mode=packages-only
```
>> Incomplete due to Failures -- Success: 282, Failure: 3

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-python-packages-machinae
        SLS: sift.python-packages.machinae
        Run#: 264
        Comment: Error installing 'machinae': Could not find a `pip` binary
      - ID: undefined
        SLS: sift.python-packages
        Run#: 283
        Comment: One or more requisite failed: sift.python-packages.machinae.sift-python-packages-machinae
      - ID: undefined
        SLS: sift.pkgs
        Run#: 284
        Comment: One or more requisite failed: sift.python-packages.sift-python-packages
```

Command: sudo sift install --pre-release --mode=packages-only
```
>> Incomplete due to Failures -- Success: 439, Failure: 8

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-python-packages-defang
        SLS: sift.python-packages.defang
        Run#: 237
        Comment: Error installing 'defang==0.5.2': Could not find a `pip` binary
      - ID: undefined
        SLS: sift.python-packages.machinae
        Run#: 238
        Comment: One or more requisite failed: sift.python-packages.defang.sift-python-packages-defang
      - ID: undefined
        SLS: sift.python-packages
        Run#: 291
        Comment: One or more requisite failed: sift.python-packages.machinae.sift-python-packages-machinae
      - ID: sift-tool-densityscout-archive
        SLS: sift.scripts.densityscout
        Run#: 335
        Comment: Error: HTTP 404: Not Found reading http://cert.at/static/downloads/software/densityscout/densityscout_build_45_linux.zip
      - ID: undefined
        SLS: sift.scripts.densityscout
        Run#: 336
        Comment: One or more requisite failed: sift.scripts.densityscout.sift-tool-densityscout-archive
      - ID: undefined
        SLS: sift.scripts.densityscout
        Run#: 337
        Comment: One or more requisite failed: sift.scripts.densityscout.sift-tool-densityscout-binary
      - ID: undefined
        SLS: sift.scripts
        Run#: 452
        Comment: One or more requisite failed: sift.scripts.densityscout.sift-tool-densityscout-link, sift.scripts.densityscout.sift-tool-densityscout-archive, sift.scripts.densityscout.sift-tool-densityscout-binary
      - ID: undefined
        SLS: sift.server
        Run#: 453
        Comment: One or more requisite failed: sift.scripts.sift-scripts, sift.python-packages.sift-python-packages
```

Command: sudo sift install
```
>> Incomplete due to Failures -- Success: 532, Failure: 10

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-python-packages-machinae
        SLS: sift.python-packages.machinae
        Run#: 264
        Comment: Error installing 'machinae': Could not find a `pip` binary
      - ID: undefined
        SLS: sift.python-packages
        Run#: 283
        Comment: One or more requisite failed: sift.python-packages.machinae.sift-python-packages-machinae
      - ID: sift-tool-densityscout-archive
        SLS: sift.tools.densityscout
        Run#: 284
        Comment: Error: HTTP 404: Not Found reading http://cert.at/static/downloads/software/densityscout/densityscout_build_45_linux.zip
      - ID: undefined
        SLS: sift.tools.densityscout
        Run#: 285
        Comment: One or more requisite failed: sift.tools.densityscout.sift-tool-densityscout-archive
      - ID: undefined
        SLS: sift.tools.densityscout
        Run#: 286
        Comment: One or more requisite failed: sift.tools.densityscout.sift-tool-densityscout-binary
      - ID: undefined
        SLS: sift.tools
        Run#: 287
        Comment: One or more requisite failed: sift.tools.densityscout.sift-tool-densityscout-archive, sift.tools.densityscout.sift-tool-densityscout-binary, sift.tools.densityscout.sift-tool-densityscout-link
      - ID: sift-pdf-guide-linux-shell-survival
        SLS: sift.config.user.pdfs
        Run#: 467
        Comment: Specified sha256 checksum for /home/sansforensics/Desktop/Linux-Shell-Survival-Guide.pdf (2d06aa1673fb9f0c7a4650a3f23753de724a98d2a2b3ded90b2e6a6a1faecd46) does not match actual checksum (15a731e1f55643ccb909c84fe4b8d8d35b0dd5de4cb0588aeca0b38f8a917ace)
      - ID: undefined
        SLS: sift.config.user
        Run#: 492
        Comment: One or more requisite failed: sift.config.user.pdfs.sift-pdf-guide-linux-shell-survival
      - ID: undefined
        SLS: sift.config
        Run#: 547
        Comment: One or more requisite failed: sift.config.user.sift-config-user
      - ID: undefined
        SLS: sift.vm
        Run#: 548
        Comment: One or more requisite failed: sift.tools.sift-tools, sift.config.sift-config, sift.python-packages.sift-python-packages
```

Command: sudo sift install --pre-release
```
>> Incomplete due to Failures -- Success: 541, Failure: 17

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-python-packages-defang
        SLS: sift.python-packages.defang
        Run#: 237
        Comment: Error installing 'defang==0.5.2': Could not find a `pip` binary
      - ID: undefined
        SLS: sift.python-packages.machinae
        Run#: 238
        Comment: One or more requisite failed: sift.python-packages.defang.sift-python-packages-defang
      - ID: undefined
        SLS: sift.python-packages
        Run#: 291
        Comment: One or more requisite failed: sift.python-packages.machinae.sift-python-packages-machinae
      - ID: sift-tool-densityscout-archive
        SLS: sift.scripts.densityscout
        Run#: 335
        Comment: Error: HTTP 404: Not Found reading http://cert.at/static/downloads/software/densityscout/densityscout_build_45_linux.zip
      - ID: undefined
        SLS: sift.scripts.densityscout
        Run#: 336
        Comment: One or more requisite failed: sift.scripts.densityscout.sift-tool-densityscout-archive
      - ID: undefined
        SLS: sift.scripts.densityscout
        Run#: 337
        Comment: One or more requisite failed: sift.scripts.densityscout.sift-tool-densityscout-binary
      - ID: undefined
        SLS: sift.scripts
        Run#: 452
        Comment: One or more requisite failed: sift.scripts.densityscout.sift-tool-densityscout-link, sift.scripts.densityscout.sift-tool-densityscout-archive, sift.scripts.densityscout.sift-tool-densityscout-binary
      - ID: undefined
        SLS: sift.server
        Run#: 453
        Comment: One or more requisite failed: sift.scripts.sift-scripts, sift.python-packages.sift-python-packages
      - ID: sift-pdf-guide-linux-shell-survival
        SLS: sift.config.user.pdfs
        Run#: 479
        Comment: Specified sha256 checksum for /home/sansforensics/Desktop/Linux-Shell-Survival-Guide.pdf (2d06aa1673fb9f0c7a4650a3f23753de724a98d2a2b3ded90b2e6a6a1faecd46) does not match actual checksum (15a731e1f55643ccb909c84fe4b8d8d35b0dd5de4cb0588aeca0b38f8a917ace)
      - ID: sift-config-terminal-profiles-file
        SLS: sift.config.user.terminal_xenial
        Run#: 489
        Comment: Source file salt://sift/config/user/files/terminal-profiles.txt not found
```

**Comment by ekristen** [comment]
A pdf and density scout changed. A new release will be coming soon to address, unfortunately I’ve been traveling.

**Comment by coonsmatthew** [comment]
I'm also experiencing this issue. It seems that forcing pip downgrade actually fixes it for me. I tried this by running a pip downgrade after a pip upgrade broke it all. I followed instructions here: https://github.com/teamdfir/sift/issues/292

**Comment by coonsmatthew** [comment]
I'm also experiencing this issue. Is there a way to get around this in the mean-time?

**Comment by ekristen** [comment]
v2019.11.0-rc1 was just pushed, but I haven't had a chance to test yet. 

Run the CLI tool with `--pre-release` to try this version.

**Comment by coonsmatthew** [comment]
I ran the test, and got an error with installing defang, see log below: 

```>> Incomplete due to Failures -- Success: 443, Failure: 4

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-python-packages-defang
        SLS: sift.python-packages.defang
        Run#: 237
        Comment: Error installing 'defang==0.5.2': Could not find a `pip` binary
      - ID: undefined
        SLS: sift.python-packages.machinae
        Run#: 238
        Comment: One or more requisite failed: sift.python-packages.defang.sift-python-packages-defang
      - ID: undefined
        SLS: sift.python-packages
        Run#: 291
        Comment: One or more requisite failed: sift.python-packages.machinae.sift-python-packages-machinae
      - ID: undefined
        SLS: sift.server
        Run#: 453
        Comment: One or more requisite failed: sift.python-packages.sift-python-packages```

But I could install the package manually: `user@host:~$ sudo pip install defang==0.5.2`

But this does not seem to fix the install issue.

**Comment by ekristen** [comment]
Is pip installed?

**Comment by coonsmatthew** [comment]
Sudo pip works (outside of the SIFT installer process).

**Comment by ekristen** [comment]
Ok. I’ll look into it

**Comment by coonsmatthew** [comment]
Any update on this @ekristen? If there's any testing that I can run to check if the build process is working, I'm happy to do it!

**Comment by ekristen** [comment]
I will be looking at this today, but for some reason the pip binary can’t be found, can you run salt-call versions-report and tell me what OS version you are on?

**Comment by coonsmatthew** [comment]
I get some interesting results: 

```
[WARNING ] /usr/lib/python2.7/dist-packages/salt/minion.py:653: DeprecationWarning: zmq.eventloop.ioloop is deprecated in pyzmq 17. pyzmq now works with default tornado and asyncio eventloops.
  io_loop = zmq.eventloop.ioloop.ZMQIOLoop()

[ERROR   ] DNS lookup or connection check of 'salt' failed.
[ERROR   ] Master hostname: 'salt' not found or not responsive. Retrying in 30 seconds 
```

**Comment by coonsmatthew** [comment]
Also, if I cat lsb-release, here's what I see: 
```DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
```

**Comment by Sandriekus** [comment]
tested it on a clean 16.04.06 version (latest updates via apt-get)

installed the cli:
`> sift-cli@1.7.1-master.f1177e4
`

sudo sift install --pre-release
`>> Incomplete due to Failures -- Success: 550, Failure: 8

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-config-terminal-profiles-file
        SLS: sift.config.user.terminal_xenial
        Run#: 489
        Comment: Source file salt://sift/config/user/files/terminal-profiles.txt not found
      - ID: undefined
        SLS: sift.config.user.terminal_xenial
        Run#: 490
        Comment: One or more requisite failed: sift.config.user.terminal_xenial.sift-config-terminal-profiles-file
      - ID: undefined
        SLS: sift.config.user.terminal
        Run#: 491
        Comment: One or more requisite failed: sift.config.user.terminal_xenial.sift-config-terminal-profiles-file, sift.config.user.terminal_xenial.sift-config-terminal-profiles-install
      - ID: sift-config-theme-set-unity-logo
        SLS: sift.config.user.theme_xenial
        Run#: 499
        Comment: Source file salt://sift/files/sift/images/login_logo.png not found
      - ID: undefined
        SLS: sift.config.user.theme
        Run#: 502
        Comment: One or more requisite failed: sift.config.user.theme_xenial.sift-config-theme-set-unity-logo
      - ID: undefined
        SLS: sift.config.user
        Run#: 508
        Comment: One or more requisite failed: sift.config.user.terminal.sift-config-user-terminal, sift.config.user.theme.sift-config-user-theme
      - ID: undefined
        SLS: sift.config
        Run#: 565
        Comment: One or more requisite failed: sift.config.user.sift-config-user
      - ID: undefined
        SLS: sift.desktop
        Run#: 566
        Comment: One or more requisite failed: sift.config.sift-config
`

sudo sift version after install
`> sift-cli@1.7.1-master.f1177e4
> sift-version: v2019.11.0-rc1
`

so it is getting better, only some errors left

**Comment by ekristen** [comment]
We do support 18.04 now. I had to rebuild my 16.04 setup, I’m running additional tests now.

**Comment by ekristen** [comment]
@Sandriekus fixed the terminal profiles bug, that's being published now in v2019.11.0-rc2

**Comment by ekristen** [comment]
16.04 confirmed working with https://github.com/teamdfir/sift-saltstack/releases/tag/v2019.11.0-rc3

**Comment by ekristen** [comment]
Please download and install https://github.com/teamdfir/sift-cli/releases/tag/v1.8.0-rc3 and then run `sift install --pre-release` or `sift upgrade --pre-release`

**Comment by Sandriekus** [comment]
on Ubuntu 16.04.6 ..

installed sift-cli 1.8.0-rc3.. success
sift install --pre-release failed:

```
(node:2547) UnhandledPromiseRejectionWarning: Error: spawn   ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:249:19)
    at onErrorNT (internal/child_process.js:442:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
(node:2547) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2547) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Sandriekus** [comment]
on Ubuntu 18.04.3:

installed sift-cli 1.8.0-rc3.. succes
sift install --pre-release failed:

```
(node:2741) UnhandledPromiseRejectionWarning: Error: spawn   ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:249:19)
    at onErrorNT (internal/child_process.js:442:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
(node:2741) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2741) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

both ubuntu 16.04.6 and 18.04.3 are clean installs

**Comment by ekristen** [comment]
@Sandriekus any other output?

**Comment by ekristen** [comment]
Please download and install https://github.com/teamdfir/sift-cli/releases/tag/v1.8.0-rc4 and then run `sift install --pre-release` or `sift upgrade --pre-release` or `sift update`. rc3 was most definitely broken due to a typo after testing before build. Sorry about that.

**Comment by Sandriekus** [comment]
yes! tested on ubuntu 16.04.06 and finished without any errors.
case closed :)

**Comment by zappeee** [comment]
> We do support 18.04 now. I had to rebuild my 16.04 setup, I’m running additional tests now.
> […](#)
> Sent from my iPhone

So 18.04 support is not in beta anymore as it says on saltstack readme?

**Comment by ekristen** [comment]
Yes and no. It’s in the latest release and it’s working for the community edition. It hasn’t been signed off for class rooms yet.

**Comment by coonsmatthew** [comment]
Confirmed it's fixed for me as well! Thanks @ekristen
