### ISSUE TITLE
Rekall 1.7.2.rc1 (Hurricane Ridge) RuntimeError (SIFT v2019.06.0)

### ISSUE THREAD

**Issue by raedeus** [teamdfir/sift#402]
I'm getting the following output when trying to run rekall:

 rekall -f memdump.aff4 imageinfo
Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 11, in <module>
    load_entry_point('rekall-core==1.7.2rc1', 'console_scripts', 'rekall')()
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/rekal.py", line 98, in main
    user_session=user_session)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/args.py", line 432, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/session.py", line 142, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall_lib/utils.py", line 1091, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/session.py", line 1062, in profile
    res = self.GetParameter("profile_obj")
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 730, in calculate
    if not self.session.plugins.load_as().GetPhysicalAddressSpace():
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/core.py", line 378, in GetPhysicalAddressSpace
    self.session.physical_address_space = self.GuessAddressSpace()
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/core.py", line 477, in GuessAddressSpace
    **kwargs)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall_lib/registry.py", line 96, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/vmem.py", line 108, in __init__
    0xbed2bed0, 0xbad1bad1, 0xbed2bed2, 0xbed3bed3],
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/obj.py", line 536, in method
    proxied = self.proxied()
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/obj.py", line 631, in proxied
    return self.v()
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/obj.py", line 653, in v
    data = self.obj_vm.read(self.obj_offset, self.obj_size)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/addrspace.py", line 488, in read
    data = self.read_partial(addr, length)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/addrspace.py", line 523, in read_partial
    chunk_number * self.CHUNK_SIZE, self.CHUNK_SIZE)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/addrspace.py", line 501, in cached_read_partial
    return super(CachingAddressSpaceMixIn, self).read(addr, length)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/addrspace.py", line 589, in read
    buf = self._read_chunk(addr, length)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/addrspace.py", line 666, in _read_chunk
    return run.address_space.read(file_offset, available_length)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/aff4.py", line 69, in read
    return self.stream.read(length)
  File "/opt/rekall/local/lib/python2.7/site-packages/pyaff4/aff4.py", line 266, in read
    return self.Read(length)
  File "/opt/rekall/local/lib/python2.7/site-packages/pyaff4/aff4_map.py", line 251, in Read
    buffer = target_stream.Read(length_to_read_in_target)
  File "/opt/rekall/local/lib/python2.7/site-packages/pyaff4/aff4_image.py", line 293, in Read
    chunks_read, data = self._ReadPartial(chunk_id, chunks_to_read)
  File "/opt/rekall/local/lib/python2.7/site-packages/pyaff4/aff4_image.py", line 379, in _ReadPartial
    data = self._ReadChunkFromBevy(chunk_id, bevy)
  File "/opt/rekall/local/lib/python2.7/site-packages/pyaff4/aff4_image.py", line 432, in _ReadChunkFromBevy
    "Unable to process compression %s" % self.compression)
RuntimeError: Unable to process compression https://tools.ietf.org/html/rfc1951

**Comment by ekristen** [comment]
Installation works for me? Please download and install https://github.com/teamdfir/sift-cli/releases/tag/v1.8.0-rc3 and then run `sift install --pre-release` or `sift upgrade --pre-release`
