### ISSUE TITLE
18.04 YUMI Multiboot fails to install

### ISSUE THREAD

**Issue by WriteCodeEveryday** [teamdfir/sift#435]
Getting an issue installing

```
ubuntu@ubuntu:~/Downloads$ sudo sift install
> sift-cli@1.8.1
> sift-version: notinstalled

Installing and configuring SaltStack properly ...
(node:14479) UnhandledPromiseRejectionWarning: Error: Command failed: apt-get install -y --allow-change-held-packages salt-minion
E: Unable to correct problems, you have held broken packages.

    at ChildProcess.exithandler (child_process.js:304:12)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1011:16)
    at Socket.<anonymous> (internal/child_process.js:416:11)
    at Socket.emit (events.js:196:13)
    at Pipe.<anonymous> (net.js:586:12)
(node:14479) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14479) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm currently not holding any broken packages
```
ubuntu@ubuntu:~/Downloads$ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

Is there a hard requirement on this being an installed version of Ubuntu versus a live version on a flash drive?

**Comment by ekristen** [comment]
I personally haven't tried a live version theoretically there shouldn't be a difference in apt that would cause this. Did you try running the install command again, it might have been a momentary problem with APT that resolved itself.

**Comment by WriteCodeEveryday** [comment]
Yeah, tried for about 2-3 days before opening the issue.

**Comment by ekristen** [comment]
@WriteCodeEveryday I just published https://github.com/teamdfir/sift-cli/releases/tag/v1.8.2 which fixes a bug with the CLI tool, can you please upgrade to it and try again, see if that changes output and provides more context.

**Comment by ekristen** [comment]
@WriteCodeEveryday if you continue to have issues please feel free to re-open.
