### ISSUE TITLE
CLI - Issue with Installing on Ubuntu 19.10

### ISSUE THREAD

**Issue by runningyogi** [teamdfir/sift#459]
I tried to install the work station on Ubuntu 19.10 this is the error:

sift install
> sift-cli@1.8.5

invalid OS, unable to determine ubuntu version
Error: invalid OS, unable to determine ubuntu version
    at validOS (/snapshot/sift-cli/sift-cli.js:160:11)
    at run (/snapshot/sift-cli/sift-cli.js:640:9)
    at main (/snapshot/sift-cli/sift-cli.js:745:11)
    at Object.<anonymous> (/snapshot/sift-cli/sift-cli.js:751:1)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:768:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at Function.Module._load (internal/modules/cjs/loader.js:553:12)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1316:12)
    at internal/main/run_main_module.js:17:11

----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy. 

Before opening an issue in GitHub, please check to see if 
your apt system is healthy.

Try running 'apt-get update' then remove any packages that 
aren't used by running 'apt-get autoremove'

**Comment by ekristen** [comment]
19.10 is not supported. 20.04 will be the next after it’s released and we have time to build out support for it.

**Comment by MMULLINIX1** [comment]
Eric, is 18.04 still supported with the Manual Install?
