### ISSUE TITLE
CLI - Issue with Installing on Ubuntu 20.04.1

### ISSUE THREAD

**Issue by vietlq414** [teamdfir/sift#483]
I tried to install the work station on Ubuntu 19.10 this is the error:

```bash
sudo sift install
```
> sift-cli@1.8.5

invalid OS, unable to determine ubuntu version
Error: invalid OS, unable to determine ubuntu version
    at validOS (/snapshot/sift-cli/sift-cli.js:160:11)
    at run (/snapshot/sift-cli/sift-cli.js:640:9)
    at main (/snapshot/sift-cli/sift-cli.js:745:11)
    at Object.<anonymous> (/snapshot/sift-cli/sift-cli.js:751:1)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:768:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at Function.Module._load (internal/modules/cjs/loader.js:553:12)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1316:12)
    at internal/main/run_main_module.js:17:11

----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy.

Before opening an issue in GitHub, please check to see if
your apt system is healthy.

Try running 'apt-get update' then remove any packages that
aren't used by running 'apt-get autoremove'

```bash
lsb_release -a
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

![Annotation 2020-08-22 215425](https://user-images.githubusercontent.com/25049349/90959026-137d7980-e4c2-11ea-958b-f40a550ecdc9.png)

**Comment by ekristen** [comment]
20.04 is not yet supported

**Comment by mrf0012** [comment]
So what versions are supported?

**Comment by ekristen** [comment]
18.04
