### ISSUE TITLE
[CLI] Update returned exit code not zero

### ISSUE THREAD

**Issue by dnabanita7** [teamdfir/sift#504]
```
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:547:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```
I use ubuntu 20.04 and am facing the above mentioned issue.

**Comment by dnabanita7** [comment]
Closing this as 20.04 is not yet supported.
