### ISSUE TITLE
sift 1.92 install fails - ModuleNotFoundError: No module named 'setuptools_rust'

### ISSUE THREAD

**Issue by eagerbeaver-ce** [teamdfir/sift#509]
Hi,
I installed ubuntu 18.0.4.5 then installed the latest updates (sudo apt-get upgrade -y).
When installing SIFT CLI 1.92, I get the following error:

```
>> Running: sift-config
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:547:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)

```

I added the saltstack.log.  Not sure, but checking it, it seems the error is based on this:

```
Collecting cryptography>=2.0 (from SecretStorage>=3.2; sys_platform == "linux"->keyring>=21.2.1->pyhindsight)
  Downloading https://files.pythonhosted.org/packages/fa/2d/2154d8cb773064570f48ec0b60258a4522490fcb115a6c7c9423482ca993/cryptography-3.4.6.tar.gz (546kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-o7t04661/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    
            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:
    
            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================
    
    
    ----------------------------------------
# [ERROR   ] stderr: The directory '/home/user/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/user/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-o7t04661/cryptography/
# [ERROR   ] retcode: 1
# [ERROR   ] Failed to install packages: pyhindsight. Error: Collecting pyhindsight
  Downloading https://files.pythonhosted.org/packages/19/2c/a39f18876a59e7c00d18e02ee987801b15ef3fc5b17fa88272052919ed9d/pyhindsight-20210116-py3-none-any.whl (1.8MB)


```

[saltstack-2.log](https://github.com/teamdfir/sift/files/6010417/saltstack-2.log)

**Comment by eagerbeaver-ce** [comment]
Seems that the file was not attached.  attaching it again here.
[saltstack-2.log](https://github.com/teamdfir/sift/files/6010398/saltstack-2.log)

**Comment by eddocode** [comment]
@eagerbeaver-ce If you are still having issues installing sift, you can give this work around a try: 
```
sudo apt update
sudo apt upgrade
sudo apt install build-essential python3-pip libssl-dev rustc curl
sudo pip3 install puremagic
sudo pip3 install pyhindsight
sudo curl -Lo /usr/local/bin/sift https://github.com/sans-dfir/sift-cli/releases/download/v1.9.2/sift-cli-linux
sudo chmod +x /usr/local/bin/sift
sudo sift install
```

**Comment by eagerbeaver-ce** [comment]
Thank you very much.  That worked.
