### ISSUE TITLE
[CLI] Issue installing SIFT on Ubuntu workstation -   except IOError, e:

### ISSUE THREAD

**Issue by ivityc** [teamdfir/sift#550]
Hi ,
I have a problem installing SIFT from cli on an existing Ubuntu workstation Ubuntu 20.04.3 LTS
I use the command **sudo sift install --mode=server**
and then I get the error below.
thaks for your help.

============================================================

sift-cli@1.13.1+0-g5ecd4f4
> sift-version: notinstalled

> mode: server
> downloading v2021.12.5
>> downloading sift-saltstack-v2021.12.5.tar.gz.asc
>> downloading sift-saltstack-v2021.12.5.tar.gz.sha256
>> downloading sift-saltstack-v2021.12.5.tar.gz.sha256.asc
>> downloading sift-saltstack-v2021.12.5.tar.gz
> validating file sift-saltstack-v2021.12.5.tar.gz
> validating signature for sift-saltstack-v2021.12.5.tar.gz.sha256
> extracting update sift-saltstack-v2021.12.5.tar.gz
> performing update v2021.12.5
>> Log file: /var/cache/sift/cli/v2021.12.5/saltstack.log

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:546:23)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

If I check the log file in /var/cache/sift/cli/v2021.12.5/saltstack.log
I see 

Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3001.8', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 439, in salt_call
    import salt.cli.call
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 6, in <module>
    import salt.cli.caller
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 19, in <module>
    import salt.minion
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 30, in <module>
    import salt.crypt
  File "/usr/lib/python3/dist-packages/salt/crypt.py", line 35, in <module>
    import salt.utils.crypt
  File "/usr/lib/python3/dist-packages/salt/utils/crypt.py", line 22, in <module>
    import Crypto.Random  # nosec
  File "/usr/local/lib/python3.8/dist-packages/Crypto/Random/__init__.py", line 28, in <module>
    from Crypto.Random import OSRNG
  File "/usr/local/lib/python3.8/dist-packages/Crypto/Random/OSRNG/__init__.py", line 32, in <module>
    from Crypto.Random.OSRNG.posix import new
  File "/usr/local/lib/python3.8/dist-packages/Crypto/Random/OSRNG/posix.py", line 66
    except IOError, e:
                  ^
SyntaxError: invalid syntax
============================================================

**Comment by ekristen** [comment]
@ivityc apologies, but somehow I didn't see this issue get opened up. 

Please see the latest version of the `sift-cli` it should fix it, but I haven't been able to reproduce this.

Are you running ubuntu 20.04? Do you happen to be WSL2?

**Comment by ivityc** [comment]
ok thanks,
the OS is Ubuntu workstation Ubuntu 20.04.3 LTS , running on a VMware esx environment. No WSL.
 I will try with the latest command version and let you know.

**Comment by ivityc** [comment]
Ok after downloading the latest sift-cli I manage to complete the installation without error. It was just complaining for inetsim as the ppa was not available, but after fixing that , it complete the setup properly.
The issue can be closed, thanks.
