### ISSUE TITLE
[CLI] WSL2 Ubuntu 22.04 Apt Errors

### ISSUE THREAD

**Issue by nullpanda** [teamdfir/sift#571]
Followed instructions at https://github.com/teamdfir/sift-cli#installation

When I run sift install --mode=server I get:

`sift install --mode=server
> sift-cli@1.14.0-rc1+0-g0582d2b

EACCES: permission denied, mkdir '/var/cache/sift'
Error: EACCES: permission denied, mkdir '/var/cache/sift'

----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy.

Before opening an issue in GitHub, please check to see if
your apt system is healthy.

Try running 'apt-get update' then remove any packages that
aren't used by running 'apt-get autoremove'`

If I run it with sudo I get:

`sift install --mode=server
> sift-cli@1.14.0-rc1+0-g0582d2b

EACCES: permission denied, mkdir '/var/cache/sift'
Error: EACCES: permission denied, mkdir '/var/cache/sift'

----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy.

Before opening an issue in GitHub, please check to see if
your apt system is healthy.

Try running 'apt-get update' then remove any packages that
aren't used by running 'apt-get autoremove'`

No packages are outdated, install -f has no available fixes, autoremove has no files to remove.

**Comment by nullpanda** [comment]
Downgrading to Ubuntu 20.04 alleviated the errors about version identification, but now hangs on the download of different components. Not sure if I am having some kind of networking issues with WSL.

**Comment by nullpanda** [comment]
And we are back:
`sudo sift install --mode=server
> sift-cli@1.14.0-rc1+0-g0582d2b
> sift-version: notinstalled

> mode: server
> downloading v2022.01.22
>> downloading sift-saltstack-v2022.01.22.tar.gz.asc
>> downloading sift-saltstack-v2022.01.22.tar.gz.sha256
>> downloading sift-saltstack-v2022.01.22.tar.gz.sha256.asc
>> downloading sift-saltstack-v2022.01.22.tar.gz
> validating file sift-saltstack-v2022.01.22.tar.gz

Hashes for sift-saltstack-v2022.01.22.tar.gz do not match. Expected: , Actual: 12d4be3e4b31690c17ed7675b11540c77b25d1c8b5a1bd5a8a15122f51984b9e  /tmp/sift-saltstack-v2022.01.22.tar.gz

Error: Hashes for sift-saltstack-v2022.01.22.tar.gz do not match. Expected: , Actual: 12d4be3e4b31690c17ed7675b11540c77b25d1c8b5a1bd5a8a15122f51984b9e  /tmp/sift-saltstack-v2022.01.22.tar.gz

    at validateFile (/snapshot/sift-cli/sift-cli.js:411:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async downloadUpdate (/snapshot/sift-cli/sift-cli.js:478:3)
    at async run (/snapshot/sift-cli/sift-cli.js:772:5)
    at async main (/snapshot/sift-cli/sift-cli.js:795:5)


----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy.

Before opening an issue in GitHub, please check to see if
your apt system is healthy.

Try running 'apt-get update' then remove any packages that
aren't used by running 'apt-get autoremove'`

**Comment by nullpanda** [comment]
Switching off the SANS conference network resolved the download errors/problems, even though I was on VPN using that network. 

Version issue still exists but 22.04 isn't officially supported, so closing issue.
