### ISSUE TITLE
[CLI] Saltstack error 'EntryPoints' object has no attribute 'items' while running sift update

### ISSUE THREAD

**Issue by 0xfaller** [teamdfir/sift#584]
Hi,

I am on the latest release of SIFT desktop (v2022.01.22). While running the update feature I do get an error (apt-get autoremove) did not fix the issue. Any knowledge what is causing the error?

Saltstack log is attached.

p.s. I am trying to fix an issue where the desktop background image did not change to SIFT image even when the initial install was successful.

Ubuntu release information:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```

SIFT version information:
```
$ cat /etc/sift-version 
v2022.01.22
```

Failed sift update:
```
$ sudo sift update --verbose
> sift-cli@1.14.0-rc1+0-g0582d2b
> sift-version: v2022.01.22

> mode: desktop
> downloading v2022.01.22
>> downloading sift-saltstack-v2022.01.22.tar.gz.asc
>> downloading sift-saltstack-v2022.01.22.tar.gz.sha256
>> downloading sift-saltstack-v2022.01.22.tar.gz.sha256.asc
>> downloading sift-saltstack-v2022.01.22.tar.gz
> validating file sift-saltstack-v2022.01.22.tar.gz
> validating signature for sift-saltstack-v2022.01.22.tar.gz.sha256
> extracting update sift-saltstack-v2022.01.22.tar.gz
> performing update v2022.01.22
>> Log file: /var/cache/sift/cli/v2022.01.22/saltstack.log

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:556:23)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)


----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy. 

Before opening an issue in GitHub, please check to see if 
your apt system is healthy.

Try running 'apt-get update' then remove any packages that 
aren't used by running 'apt-get autoremove']
```
[saltstack.log](https://github.com/teamdfir/sift/files/10054813/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @0xfaller , the issue lies with the latest version of Salt and one of the dependencies which was upgraded. To resolve the issue, you can run:
`sudo python3 -m pip install "importlib-metadata<5.0.0"` 

Let me know how that goes!
