### ISSUE TITLE
SIFT Run Error Message after install

### ISSUE THREAD

**Issue by Dahicup1** [teamdfir/sift#604]
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Traceback (most recent call last):
  File "/usr/bin/sift", line 33, in <module>
    sys.exit(load_entry_point('guiqwt==4.0.1', 'gui_scripts', 'sift')())
  File "/usr/lib/python3/dist-packages/guiqwt/tests/sift.py", line 1603, in run
    window = MainWindow()
  File "/usr/lib/python3/dist-packages/guiqwt/tests/sift.py", line 1420, in __init__
    self.curvewidget = DockablePlotWidget(self, CurveWidget, curveplot_toolbar)
  File "/usr/lib/python3/dist-packages/guiqwt/tests/sift.py", line 1365, in __init__
    self.plotwidget = plotwidgetclass()
  File "/usr/lib/python3/dist-packages/guiqwt/plot.py", line 846, in __init__
    super(CurveWidget, self).__init__(
  File "/usr/lib/python3/dist-packages/guiqwt/plot.py", line 799, in __init__
    self.plot = CurvePlot(
  File "/usr/lib/python3/dist-packages/guiqwt/curve.py", line 1450, in __init__
    self.cross_marker = Marker()
  File "/usr/lib/python3/dist-packages/guiqwt/shapes.py", line 301, in __init__
    self.markerparam.update_marker(self)
  File "/usr/lib/python3/dist-packages/guiqwt/styles.py", line 1579, in update_marker
    symb.update_symbol(obj)
  File "/usr/lib/python3/dist-packages/guiqwt/styles.py", line 453, in update_symbol
    obj.setSymbol(self.build_symbol())
  File "/usr/lib/python3/dist-packages/qwt/plot_marker.py", line 405, in setSymbol
    self.setLegendIconSize(symbol.boundingRect().size())
  File "/usr/lib/python3/dist-packages/qwt/symbol.py", line 1234, in boundingRect
    r.setLeft(np.floor(rect.left()))
_TypeError: setLeft(self, int): argument 1 has unexpected type 'numpy.float64'_**_
[SIFT_Error_Message.txt](https://github.com/teamdfir/sift/files/12448908/SIFT_Error_Message.txt)
[SIFT_Error_Message.txt](https://github.com/teamdfir/sift/files/12448909/SIFT_Error_Message.txt)

**Comment by digitalsleuth** [comment]
Hi there @Dahicup1 , it looks like you have another tool installed using the same name (`sift`), looks like it's [this tool](https://github.com/PierreRaybaut/guiqwt). To avoid this conflict, you can rename the CLI installer to `sift-cli` or anything else, and use the command that way.

**Comment by digitalsleuth** [comment]
Hi @Dahicup1 , did you manage to get this sorted out?
