### ISSUE TITLE
Error when installing Sift

### ISSUE THREAD

**Issue by Wolejarz79** [teamdfir/sift#611]
I attempted to install Sift on a Laptop running Ubuntu 20.0.4 and received the following error on install. 

> mode: desktop
Installing and configuring SaltStack properly ...
> downloading v2023.02.06
>> downloading sift-saltstack-v2023.02.06.tar.gz.asc
/snapshot/sift-cli/sift-cli.js:357
          throw new Error(res.body)
          ^

Error
    at Request.<anonymous> (/snapshot/sift-cli/sift-cli.js:357:17)
    at Request.emit (events.js:400:28)
    at Request.onRequestResponse (/snapshot/sift-cli/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:206:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
wbforensics@wbforensics:~/Downloads$ sudo sift install
> sift-cli@1.14.0-rc1+0-g0582d2b
> sift-version: notinstalled

Any insight into what when wrong?

Thanks

**Comment by digitalsleuth** [comment]
Hi @Wolejarz79 , the sift-cli has been deprecated in favor of [Cast](https://github.com/ekristen/cast). For instructions on how to install SIFT after installing cast, please [see the instructions here](https://github.com/teamdfir/sift#installation).

Cheers!

**Comment by Wolejarz79** [comment]
Thank you. I was able to create the sift workstation with Cast.


William Olejarz
Cybersecurity Analyst/Technology Support

[3AF1A5D5]
229 Exchange Street
Chicopee, MA 01013
Office (413)564-2691
IS Help Desk (413) 568-1911 x4357
